### PR TITLE
virtual text support

### LINKED ISSUE #14: feat: inline virtual text suggestion similar to `codeium.vim` project
Awesome plugin, thank you a lot.

Would it be possible to get suggestions the same way as in `codeium.vim` project? `cmp` is awesome but you need start typing or press C-Space to see suggestions, and suggestions are shown not in the first positions of a long list.

### PR DESCRIPTION
**Pull request by dimfeld**
This is a port of the virtual text support from codeium.vim. 

To enable it, pass `virtual_text = { enabled = true }` in your setup arguments to the plugin. The README has more details.

Closes #14

### CODE REVIEW

**Comment by dimfeld** [comment]
I think this is ready to go. Been using it today in my development and it's looking good I think

**Comment by dimfeld** [comment]
Rebased on latest main

**Comment by dro-sh** [comment]
@dimfeld I use your fork at my config and have tab use hotkey for apply suggestion. But it is conflict with tab indent and I have next error, then I want to add tab indent where is no suggestion from codeium: 
```
Error executing lua: ....local/share/nvim/lazy/nvim-cmp/lua/cmp/utils/keymap.lua:267: "replace_keycodes" requires "expr"
stack traceback:
        [C]: in function 'nvim_set_keymap'
        ....local/share/nvim/lazy/nvim-cmp/lua/cmp/utils/keymap.lua:267: in function 'set_map'
        ....local/share/nvim/lazy/nvim-cmp/lua/cmp/utils/keymap.lua:185: in function 'solve'
        ....local/share/nvim/lazy/nvim-cmp/lua/cmp/utils/keymap.lua:148: in function <....local/share/nvim/lazy/nvim-cmp/lua/cmp/utils/keymap.lua:147>
```

**Comment by dimfeld** [comment]
Could you give more details please? Also that error seems to be coming from `cmp` which the virtual text doesn't use.

**Comment by dimfeld** [comment]
@zenofile Thanks for the report! I installed oil.nvim and was able to reproduce this, so I made 2 changes:

1. Detect if the buffer's filename is a URI (like the Oil buffer has a filename of `oil://home/user`) and don't try to do completions in that case. This is actually what was causing the error
2. Add `filetypes` to the virtual text config so you can turn it on and off for specific filetypes.

**Comment by yatinlala** [comment]
So happy to see this feature! Thanks for the great work @dimfeld. 🙏

I think there has been a regression in a recent commit — <Esc> in normal mode from insert is broken.

Pressing <Esc> in insert mode doesn't return me to normal mode. Setting `virtual_text = { enabled = false }` restores normal functionality.

Minimal conf to reproduce:
```
local lazypath = vim.fn.stdpath('data') .. '/lazy/lazy.nvim'
if not (vim.uv or vim.loop).fs_stat(lazypath) then
  local lazyrepo = 'https://github.com/folke/lazy.nvim.git'
  local out = vim.fn.system({ 'git', 'clone', '--filter=blob:none', '--branch=stable', lazyrepo, lazypath })
  if vim.v.shell_error ~= 0 then
    vim.api.nvim_echo({
      { 'Failed to clone lazy.nvim:\n', 'ErrorMsg' },
      { out, 'WarningMsg' },
      { '\nPress any key to exit...' },
    }, true, {})
    vim.fn.getchar()
    os.exit(1)
  end
end
vim.opt.rtp:prepend(lazypath)

-- Setup lazy.nvim
require('lazy').setup({
  'dimfeld/codeium.nvim',
  branch = 'virtual-text',
  lazy = false,
  dependencies = {
    'nvim-lua/plenary.nvim',
  },
  opts = {
    enable_cmp_source = false,
    virtual_text = {
      enabled = true,
    },
  },
})

```

**Comment by dimfeld** [comment]
@yatinlala which key was affected that doesn’t go back into insert mode? I think GitHub maybe stripped out whatever you wrote there.  Esc works fine for me, is there another key you would expect to do that?

**Comment by yatinlala** [comment]
Seems like it got stripped — Esc doesn't work for me. I can try and bisect tomorrow to the problem commit.

**Comment by dimfeld** [comment]
Ok I do see the same issue with that bare config, just not with the one I normally use. Interesting... I'll look into it. Thanks!

**Comment by dimfeld** [comment]
Ok should be fixed now. Turns out that  `C-[` is the same keycode as Esc, and I had that set as the default keycode for Clear. So when I fixed a bug that it wasn't setting the Clear keycode properly it started actually mapping Esc to clear.

**Comment by saranshsaini** [comment]
Thanks for adding this, super cool. Im about ready to merge it in if you think it is done.
The only thing I wanted to bring up is that when your cursor is on an empty line the virtual text shows up the line below it. Would it be an easy fix to put it on the same line as the cursor? Pic attached
image

**Comment by dimfeld** [comment]
Yeah I think it's all ready to go!  So I'm only seeing that extra line in cases where it looks like the Codeium completion is actually trying to insert a newline for formatting purposes. For example here an extra newline makes sense, and when I accept the completion it adds it.

CleanShot 2024-10-21 at 15 42 09@2x

But then if I already have appropriate whitespace then it doesn't, like here:

CleanShot 2024-10-21 at 15 42 30@2x

So I think this is actually coming from Codeium itself. That said, I can try to add something to strip out leading newlines if you think that's not desirable.

**Comment by saranshsaini** [comment]
If that's the case then all good.
I'll test this on windows soon and then it should be good to merge.

**Comment by saranshsaini** [comment]
Tested on windows but got an error. I think its because this branch doesnt include the fixes in #248 . Ill approve and when you merge in should be sorted out.

**Review by saranshsaini — APPROVED** [review]

**Pull request merged**
