### PR TITLE
feat: Adding healthcheck module with api and server status

### PR DESCRIPTION
**Pull request by gmatheu**
Adding default healt check module

By executing the command:
`checkhealth codeium`

Right after starting Neovim, you will get something like:

After a couple of seconds, when the server is started:

### CODE REVIEW

**Comment by pqn** [comment]
Cool!

**Comment by pqn** [comment]
Could you undo the formatting changes?

**Comment by xafarr** [comment]
@gmatheu any update on this?

**Comment by gmatheu** [comment]
> Could you undo the formatting changes?

Sure, my bad...  I'll push changes later

**Comment by gmatheu** [comment]
> @gmatheu any update on this?

As it is, is useful for the purpose.

Ther is a couple of improvements that can be applied later (such as showing the log file location, currently is encapsulated in the log module)

**Comment by gmatheu** [comment]
> Could you undo the formatting changes?

Done. For some reason I had to add a **stylua.toml** file for proper format to applied

**Review by pqn — APPROVED** [review]

**Pull request merged**
