### PR TITLE
Add workspace context to chat

### PR DESCRIPTION
**Pull request by aliaksandr-trush**
Fix issues:  #170

Known issues:
- [x]  I do not have NixOS and unable to provide correct hash256 values for the server
- [x]  Unable to add path to a hidden workspace. Error code returning from the server.
- [x]  The same path would be added one Codeium Chat command that's causing error code

### CODE REVIEW

**Comment by aliaksandr-trush** [comment]
Hash values updated. Calculated via 'nix-hash --type sha256 --sri' command. Please check correctness.

**Comment by mrheinen** [comment]
This also adds Chat to the autocomplete which was missing.

**Comment by pqn** [comment]
@aliaksandr-trush I have separately updated the hashes in the repo so you won't need to change them in this PR now.

**Comment by aliaksandr-trush** [comment]
> @aliaksandr-trush I have separately updated the hashes in the repo so you won't need to change them in this PR now.

Thank you! I've rebased my changes

**Review by pqn — APPROVED** [review]

**Pull request merged**
