### PR TITLE
Add :Codeium Chat

### PR DESCRIPTION
**Pull request by consoleaf**
So far this only opens the chat interface in the default web browser. ~~On my system the chat doesn't work, giving me errors about openai, but it might for you.~~

upd: Chat works now, but it seems like for it to be context aware I need to be calling `AddTrackedWorkspace`

### CODE REVIEW

**Comment by consoleaf** [comment]
Correction: in enterprise mode it gives me errors but lets me send prompts.
In non-enterprise mode pressing Enter does nothing, same as in https://github.com/Exafunction/codeium.vim/pull/317

**Comment by vphantom** [comment]
FYI all these quirks were addressed on the Vim side in the PR you referenced. You might want to add the missing variable(s) in your URL and try again to see if it also fixes the Enterprise side of things.

**Comment by pqn** [comment]
@consoleaf Excited for this PR. I noticed it's still a draft -- do you want to merge this as is, or also implement `AddTrackedWorkspace`?

**Comment by consoleaf** [comment]
Feel free to merge this, I'll add the workspace detection later on as a separate PR

**Review by pqn — APPROVED** [review]

**Comment by khaneliman** [comment]
> Could someone share how to make use of the chat functionality ? I understand you need to enable it in the config but how do you get it to open the browser?

Title of the PR, :Codeium Chat. But, it only is supported for xdg-open atm

**Pull request merged**
