### PR TITLE
feat: Add enterprise mode support

### PR DESCRIPTION
**Pull request by consoleaf**
Hi! I made this based on how the Visual Studio extension launches the language server. Seems to work on my setup, any feedback would be greatly appreciated. Thanks!

Addresses #113

### CODE REVIEW

**Review by fortenforge — APPROVED** [review]

**Comment by fortenforge** [comment]
Had to revert this as it caused https://github.com/Exafunction/codeium.nvim/issues/142

can you verify that this works even if you don't configure `api`? / are using codeium free

**Comment by lessthanseventy** [comment]
> Had to revert this as it caused #142
> 
> can you verify that this works even if you don't configure `api`? / are using codeium free

https://github.com/Exafunction/codeium.nvim/issues/142#issuecomment-1934978022

I'm still having issues even after the revert. Is it possibly something else?

**Comment by consoleaf** [comment]
Could you provide your config for reproduction?

**Comment by consoleaf** [comment]
Also yes, I will test this more extensively tomorrow and report back.

**Comment by lessthanseventy** [comment]
https://github.com/lessthanseventy/launch_scout.nvim/blob/8714eef087d0ffd7ef6d08dc4b0ca635e96372d9/lua/plugins/lsp/init.lua#L280

```
  {
    "jcdickinson/codeium.nvim",
    dependencies = {
      "nvim-lua/plenary.nvim",
    },
    config = function()
      require("codeium").setup({
        tools = {
          language_server = "/usr/local/bin/codeium",
        },
      })
    end,
  },
```
happens with and without the tools config.

**Pull request merged**
